<?php


namespace app\weixin\controller;

use think\Controller;
use think\Request;
use EasyWeChat\Factory;

class Common extends Controller
{

    protected $config;

    protected $app;

    public function initialize()
    {
        $this->config = [
            'app_id' => 'wx1b52115dfa323af9',
            'secret' => '9e35a003b0e77ed0c3aec6a49a4317f7',
            'token' => 'fgc2020',
            'response_type' => 'array',
            //...
        ];

        $this->app = Factory::officialAccount($this->config);
        parent::initialize(); //TODO: Change the autogenerated stub
    }

}
